export const todoText: string[] = [
  "Go for a run",
  "Call mom",
  "Buy groceries",
  "Finish the presentation",
  "Clean the house",
  "Walk the dog",
  "Do the laundry",
  "Pick up mail",
  "#shopping Milk",
  "#shopping Eggs",
  "#shopping Sugar",
  "#shopping Cereal",
  "#work Update hours on JIRA",
  "#work Finish the presentation",
  "#work Send out the emails",
  "#work Update the website",
  "#work Schedule the meeting",
  "#work Write the report",
  "#work Prepare the documents",
  "#work Submit the proposal",
  "#chores Do the dishes",
  "#chores Take out the trash",
  "#chores Mow the lawn",
  "#chores Water the plants",
  "#chores Clean the bathroom",
  "#chores Vacuum the floors",
  "#chores Dust the furniture",
  "#chores Sweep the porch",
  "#chores Organize the garage",
  "#chores Wash the car",
  "#house Paint the walls",
  "#house Fix the roof",
  "#house Install the lights",
  "#house Replace the windows",
  "#house Renovate the kitchen",
  "#house Redecorate the living room",
  "#house Landscape the yard",
  "#house Remodel the bathroom",
  "#house Build the deck",
  "#house Furnish the bedroom",
  "#house Decorate the nursery",
];
